name: hokok
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  flutter_bloc: ^8.1.2
  dio: ^5.0.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.4.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  flutter_screenutil: ^5.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: googleFont
      fonts:
        - asset: assets/font/googlefont.ttf

